Created basic webhook documentation
sodadata/docs pull request #348
Opened 2022-08-24 19:25 UTC by janet-can

For webhook documentation, we can offer the basic instructions on how to set up the integration and guidance for completing the steps. Ideally, we can also offer examples for setting up an incoming webhook.

2022-09-02 09:39 UTC, dirkgroenen commented
@janet-can I've pushed a minor change to the docs including the recently added `incidentLinkCallbackUrl`. This property can be used as an alternative to the `incidentCreated` response allowing the users to set a "link" on the Incident. 

Please check the updated Feature Spec for a more detailed explanation of its behavior. If you want to sync on it to fully understand it please let me know. See https://sodadata.slite.com/app/docs/kMPrF-8aGCHdPh#813536cc.

Afaic the Webhook Feature will be released after this sprint, being next week.

2022-09-08 08:49 UTC, dirkgroenen requested changes
Did one last final review and spotted a few things - apart from that all looks good

2022-09-08 08:49 UTC, dirkgroenen commented on soda/integrate-webhooks.md
> +4. In the **Add Integration** dialog box, select **Webhook** then follow the guided steps to configure the integration. Reference the following tables for guidance on the values to input in the guide
Missed this in the first iteration, but this is not actually required. We set the `Content-type` header to `application/json` by default behind the scenes (since the user can't alter the content-type). 

(This might give the impression that the user can alter the `content-type` header, which isn't the case)

2022-09-08 08:49 UTC, dirkgroenen commented on soda/integrate-webhooks.md
> +Soda Cloud incident integrations make use of the following events:
I think this should be `Soda Cloud alert notifications make use [...]`?

2022-09-08 08:49 UTC, dirkgroenen commented on soda/integrate-webhooks.md
> +* [`validate`](#validate)
I'll leave this to you, but we might want to setup a seperate section for the `validate` even since we don't pro-actively send it. It can only be send during the onboarding or editing of a Webhook Integration.

2022-09-08 08:49 UTC, dirkgroenen commented on soda/integrate-webhooks.md
> +  "incidentLinkCallbackUrl": "https://dev.sodadata.io/integrations/webhook/8224bbc2-2c80-4c6d-a002-16907465484e/incident-link/510fad8c-dc43-419a-a122-712a23f27197/uLYosxWNwVGHSdR-_noJjlNAA--WyQwe1ygq
Let's make sure to replace `dev.sodadata.io` for `cloud.soda.io` so we don't expose our dev environment in the docs 👼

2022-09-08 08:49 UTC, dirkgroenen commented on soda/integrate-webhooks.md
> +// > POST https://dev.sodadata.io/integrations/webhook/8224bbc2-2c80-4c6d-a002-16907465484e/incident-link/510fad8c-dc43-419a-a122-712a23f27197/uLYosxWNwVGHSdR-_noJjlNAA--WyQwe1ygqGBgZclD9Kr6rvMcIrQ
Let's make sure to replace `dev.sodadata.io` for `cloud.soda.io` so we don't expose our dev environment in the docs 👼

2022-09-08 08:49 UTC, dirkgroenen commented on soda/integrate-webhooks.md
> +![webhook-jira2](/assets/images/webhook-jira2.png){:height="700px" width="700px"}
The image seems to be containing the wrong body and headers, here's a screenshot of a working one: 

![image](https://user-images.githubusercontent.com/1001391/189078384-bb33368d-aa51-4b40-8229-b1364a800053.png)

2022-09-08 17:03 UTC, janet-can commented on soda/integrate-webhooks.md
> +4. In the **Add Integration** dialog box, select **Webhook** then follow the guided steps to configure the integration. Reference the following tables for guidance on the values to input in the guide
Ah, OK! Sorry, I had that in there from when I was testing and needed looooong ago. I shall remove.

2022-09-08 17:05 UTC, janet-can commented on soda/integrate-webhooks.md
> +| HTTP Headers, Value |  **Required** Enter `application/json` |
Perfect. Added!

2022-09-08 17:05 UTC, janet-can commented on soda/integrate-webhooks.md
> +Soda Cloud incident integrations make use of the following events:
Yep. :D Sharp eye!

2022-09-08 17:06 UTC, janet-can commented on soda/integrate-webhooks.md
> +  "incidentLinkCallbackUrl": "https://dev.sodadata.io/integrations/webhook/8224bbc2-2c80-4c6d-a002-16907465484e/incident-link/510fad8c-dc43-419a-a122-712a23f27197/uLYosxWNwVGHSdR-_noJjlNAA--WyQwe1ygq
got it.

2022-09-08 17:08 UTC, janet-can commented on soda/integrate-webhooks.md
> +* [`validate`](#validate)
Hm. I think I'll leave it for now. I could a section but it wouldn't have very much useful content, as the event payload and the label kind of say it all. Will see if questions emerge on the events.

2022-09-08 17:08 UTC, janet-can commented on soda/integrate-webhooks.md
> +// > POST https://dev.sodadata.io/integrations/webhook/8224bbc2-2c80-4c6d-a002-16907465484e/incident-link/510fad8c-dc43-419a-a122-712a23f27197/uLYosxWNwVGHSdR-_noJjlNAA--WyQwe1ygqGBgZclD9Kr6rvMcIrQ
Got it.

2022-09-08 17:09 UTC, janet-can commented on soda/integrate-webhooks.md
> +![webhook-jira2](/assets/images/webhook-jira2.png){:height="700px" width="700px"}
I'm going to replace the whole thing with the version Mathisse got working with the status updates.

2022-09-12 15:15 UTC, merged