Experimental docs for deploying an agent on multiple cloud services providers
sodadata/docs pull request #385
Opened 2022-10-04 17:19 UTC by janet-can

…oviders

2022-11-23 07:12 UTC, jmarien reviewed
For the overview diagram:

- maybe mark the traffic from the CLI laptop icon to the cluster as encrypted as well?
- maybe better to rename "Key vault" to a more generic "Secrets vault" ?

2022-11-23 07:12 UTC, jmarien commented on soda-agent/basics.md
> +The **Soda Agent** is a tool that empowers Soda Cloud users to securely access data sources to scan for data quality. Create a Kuberenets cluster in a cloud services provider environment, then use He
typo "Kuberenets"

2022-11-23 10:23 UTC, jmarien requested changes

2022-11-23 10:23 UTC, jmarien commented on soda-agent/upgrade.md
maybe we should put the step on how to get the current values for the deploy (see troubleshoot at the bottom) up here, so users can get the values upfront if they are in doubt?

2022-11-23 10:23 UTC, jmarien commented on soda-agent/redeploy.md
> +For example, in the following URL, the agent ID is the long UUID at the end. `https://dev.sodadata.io/agents/842feab3-snip-87eb-06d2813a72c1`.
for security reasons, I would not show dev.sodadata.io URL's as example in docs.

2022-11-23 10:23 UTC, jmarien commented on soda-agent/redeploy.md
> +
maybe we should show the "how to get the current values" step here too? So users can get these and use them for redeploy as well.

2022-11-23 10:23 UTC, jmarien commented on soda-agent/redeploy.md
> +
as an alternative option, you can run (you need the base64 cli tool for this to work):

```
kubectl get secret/soda-agent-id -n soda-agent --template={{.data.SODA_AGENT_ID}} | base64 --decode
```

2022-11-23 10:23 UTC, jmarien commented on soda-agent/helpful-commands.md
> +If you used Minikube to create a cluster, prepend all of the commands below with `minikube` and add `--` before the action. <br />
I would omit this

2022-11-23 10:23 UTC, jmarien commented on soda-agent/helpful-commands.md
> +* Use `get pods` to retrieve a list of the pods running in your cluster, including some information about each.
I would add:

"Pods are created as a result of the deployments of the Orchestrator and Scan Launcher and are created when Jobs and CronJobs are created by the Soda Agent Orchestrator."

2022-11-23 10:23 UTC, jmarien commented on soda-agent/helpful-commands.md
> +For example, the following command reveals the activity during set up of the practice pod of `nybusbreakdown` data.
"... of the practice pod of `nybusbreakdown` data, by specifying a label."

2022-11-23 10:23 UTC, jmarien commented on soda-agent/helpful-commands.md
> +```
Maybe add:

Using this alternative, the logs are retrieved using the label for the Orchestrator:
```
kubectl logs -l agent.soda.io/component=orchestrator -n soda-agent
```

and this one uses the label for the Scan Launcher pods:
```
kubectl logs -l agent.soda.io/component=scanlauncher -n soda-agent
```

2022-11-23 10:23 UTC, jmarien commented on soda-agent/helpful-commands.md
> +* In the example above that gets the pods of the soda-agent namespace, the output displays `2/2` which means that two containers are running in the pod. This indicates that a <a href="https://medium.
the sidecar's use is undocumented for most users and only enabled when a DataDog API key is specified, something we only do for internal Agent's and some Agent's for customers (like NNIP) only. 

So maybe better to omit this for now?

2022-11-25 18:14 UTC, janet-can commented on soda-agent/basics.md
> +* a **Soda Agent Orchestrator** from a Docker image, which creates Kubernetes Jobs and cron jobs to trigger scheduled scans of data
Got it. Changed to meet both suggestions.

2022-11-25 18:17 UTC, janet-can commented on soda-agent/basics.md
> +**Soda Agent** is Soda Core that you deploy in a Kubernetes cluster in your own cloud services provider environment. Deploying the agent not only installs Soda Core, it also installs two other things
Got both.

2022-11-25 18:19 UTC, janet-can commented on soda-agent/basics.md
> +**Kubernetes** is a system for orchestrating containerized applications; a **Kubernetes cluster** is a set of resources that support an application environment.
Nit-picking is my middle name.

2022-11-25 18:25 UTC, janet-can commented on soda-agent/basics.md
> +You need a Kubernetes cluster in which to deploy the containerized applications that make up the **Soda Agent**. Depending on your cloud services provider, you store sensitive values, such as login c
Got it.

2022-11-25 18:30 UTC, janet-can commented on soda-agent/deploy.md
> +* You have installed <a href="https://docs.docker.com/get-docker/" target="_blank">Docker</a> in your local environment.
Whew, OK, good. I added, then deleted, then added like 6 times. Will remove.

2022-11-25 18:32 UTC, janet-can commented on _includes/agent-api-keys.md
> +The Soda Agent communicates with your Soda Cloud account using API public and private keys. Note that the keys a Soda Agent uses are different from the API keys Soda Cloud uses to connect to Soda Cor
Ha! Right you are!

2022-11-25 18:45 UTC, janet-can commented on soda-agent/deploy.md
> +1. Install <a href="https://minikube.sigs.k8s.io/docs/start/" target="_blank">minikube</a> to use to create a Kubernetes cluster running locally.
I made it much clearer that this is an example that uses Minikube but you can use anything else you like to create or use an existing cluster.

2022-11-25 18:51 UTC, janet-can commented on soda-agent/deploy.md
> +TBD
I see what you mean. I decided to keep the cloud provider-specific troubleshooting stuff embedded in each deploy page, but added a reference to the Helpful kubctl commands page. The commands to help you get logs etc. isn't what I would call troubleshooting per se, but those commands can help you to troubleshoot in a generalize way. I figure this covers the bases and will help someone help themselves.

2022-11-25 18:54 UTC, janet-can commented on soda-agent/deploy-aws.md
> +4. Run the following command to change the context to associate the current namespace to `soda-agent`.
Umm.. I don't think I follow..  I thought I was using the explicit `soda-agent` namespace in all the example commands. What am I missing here?

2022-11-25 19:05 UTC, janet-can commented on soda-agent/deploy-azure.md
> +This setup enables Soda Cloud users to securely connect to data sources (Snowflake, Amazon Athena, etc.) from within the Soda Cloud web application. Any user in your Soda Cloud account can add a new
Heh, good call :)

2022-11-25 19:13 UTC, janet-can commented on soda-agent/deploy-azure.md
> +```
Yuck, you're right. I had separated the procedure at one point thinking it was too long and I should break it up, but then put the "create cluster" instructions incorrectly under the "deploy agent to virtual cluster" section. Doh. 
I've fixed it up now so it's accurate.

2022-11-25 19:15 UTC, janet-can commented on soda-agent/deploy-azure.md
> +
Yeah, sorry, my mistake! I've fixed it up.

2022-11-25 19:19 UTC, janet-can commented on soda-agent/deploy-azure.md
> +```
Yes, I created two separate deploy procedures, one for a regular cluster and one for a virtual cluster, so as to include the target for the virtual one: `  --set soda.agent.target=azure-aks-virtualnodes \`
I think that was the only difference between helm deploy steps, no?

2022-11-25 19:19 UTC, janet-can commented on soda-agent/deploy-aws.md
> +  --set soda.agent.target=aws-eks \
KK. Will watch for it.

2022-11-25 19:20 UTC, janet-can commented on soda-agent/deploy-gcp.md
> +---
Indeed. That part is standing by for instructions; there's nothing here but a skeleton of the layout for now.

2022-11-25 19:25 UTC, janet-can commented on soda-agent/upgrade.md
Added as a proper step, first in the procedure.

2022-11-25 19:26 UTC, janet-can commented on soda-agent/redeploy.md
> +For example, in the following URL, the agent ID is the long UUID at the end. `https://dev.sodadata.io/agents/842feab3-snip-87eb-06d2813a72c1`.
Yikes, you're right! Removed.

2022-11-25 19:29 UTC, janet-can commented on soda-agent/redeploy.md
> +
How to get the current values of the API keys? If so, then good, I added that.

2022-11-25 19:31 UTC, janet-can commented on soda-agent/helpful-commands.md
> +If you used Minikube to create a cluster, prepend all of the commands below with `minikube` and add `--` before the action. <br />
This is the Every Page is Page One bit. It is highly unnecessary if you have been reading other Soda Agent docs, but essential in giving you a shred of context for this page in the documentation if this is somehow the first page you landed on from a search result. 

But I'll remove the `--minikube` bit.

2022-11-25 19:38 UTC, janet-can commented on soda-agent/helpful-commands.md
> +* Use `get pods` to retrieve a list of the pods running in your cluster, including some information about each.
Modified the sentence slightly and added.

2022-11-25 19:43 UTC, janet-can commented on soda-agent/helpful-commands.md
> +* In the example above that gets the pods of the soda-agent namespace, the output displays `2/2` which means that two containers are running in the pod. This indicates that a <a href="https://medium.
Removed!

2022-11-26 00:34 UTC, janet-can commented on soda-agent/deploy-gcp.md
> +---
I just removed the doc. Will add new when it's ready to go.

2022-11-28 09:12 UTC, jmarien commented on soda-agent/redeploy.md
> + kubectl get secret/soda-agent-id -n soda-agent --template={{.data.SODA_AGENT_ID}} | base64 --decode
In the Netlify preview, the `{{.data.SODA_AGENT_ID}}` is not shown, probably this needs to be escaped for Jekyll?

2022-11-28 09:12 UTC, jmarien commented on soda-agent/redeploy.md
> +
Retrieving the deployed values:

```
helm get values -n soda-agent soda-agent
```

Retrieving the used API key:

```
kubectl get secret/soda-agent-apikey -n soda-agent --template={{.data.SODA_API_KEY_ID}} | base64 --decode
```

and for the API secret:

```
kubectl get secret/soda-agent-apikey -n soda-agent --template={{.data.SODA_API_KEY_SECRET}} | base64 --decode
```

2022-11-28 21:29 UTC, janet-can commented on soda-agent/redeploy.md
> + kubectl get secret/soda-agent-id -n soda-agent --template={{.data.SODA_AGENT_ID}} | base64 --decode
Yuck. I had to fight with that a few times. I'll get it to work.

2022-11-28 21:42 UTC, janet-can commented on soda-agent/redeploy.md
> +
Added the alternatives for getting deployed values.

2022-11-29 10:51 UTC, dakue-soda requested changes

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/secrets.md
> +```
```suggestion
```yaml
soda:
  apikey:
    id: "your-agent-api-key-id"
    secret: "your-agent-api-key-secret"
  agent:
    name: "your-unique-agent-name"
```
```

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/secrets.md
> +```
```suggestion
```yaml
soda:
  apikey:
    id: "your-agent-api-key-id"
    secret: "your-agent-api-key-secret"
  agent:
    name: "your-unique-agent-name"
  env:
    POSTGRES_USER: "sodacore"
    POSTGRES_PASS: "sodacore"
```
```

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/redeploy.md
> +```
```suggestion
```yaml
soda:
  apikey:
    id: "your-agent-api-key-id"
    secret: "your-agent-api-key-secret"
  agent:
    id: "842feab3-snip-87eb-06d2813a72c1"
    name: "your-unique-agent-name"
```
```

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/deploy.md
> +          replicas: 1
```suggestion
  apikey:
    id: "your-agent-api-key-id"
    secret: "your-agent-api-key-secret"
  agent:
    name: "your-unique-agent-name"
  core:
    idle: true
    replicas: 1
```

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/deploy.md
> +  --set soda.agent.target=minikube \
This is not needed because the default value here is `default` and it just needs to be different to `aws-eks` so leaving this out will also work.

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/deploy.md
>    --set soda.agent.name=myuniqueagent \
Should we make these consistent with the options in the value file?
```
--set soda.agent.name=your-unique-agent-name \
--set soda.apikey.id=your-agent-api-key-id \
--set soda.apikey.secret=your-agent-api-key-secret \
```

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/deploy-aws.md
> +```
```suggestion
```yaml
soda:
 apikey:
    id: "your-agent-api-key-id"
    secret: "your-agent-api-key-secret"
 agent:
    name: "your-unique-agent-name"
 core:
   idle: true
   replicas: 1
```
```

2022-11-29 10:51 UTC, dakue-soda commented on soda-agent/deploy-azure.md
> +```
```suggestion
```yaml
soda:
 apikey:
   id: "your-agent-api-key-id"
   secret: "your-agent-api-key-secret"
 agent:
   name: "your-unique-agent-name"
 core:
   idle: true
   replicas: 1
```
```

2022-11-30 18:19 UTC, janet-can commented on soda-agent/deploy.md
> +  --set soda.agent.target=minikube \
Got it-- removed.

2022-11-30 18:22 UTC, janet-can commented on soda-agent/deploy.md
>    --set soda.agent.name=myuniqueagent \
Good call; I adjusted to match the values between the values YAML and the CLI settings values.

2022-12-01 11:34 UTC, jmarien commented on _includes/agent-helm-command.md
> +| `--namespace soda-agent` | Use the namespace value to identify the namespace in which to deploy the agent.
Maybe we should mark soda.agent.target, soda.core.idle=true and soda.core.replicas=1 as optional

2022-12-01 11:34 UTC, jmarien commented on soda-agent/deploy-azure.md
> +```
yes, that's the only difference for the Helm commands used, indeed. The virtual nodes option also has the additional subnet created for example, but that is already clearly shown in those instructions.

2022-12-01 19:02 UTC, janet-can commented on soda-agent/deploy-azure.md
> +```
Good, I think we're in good shape, then.

2022-12-01 19:05 UTC, janet-can commented on _includes/agent-helm-command.md
> +| `--namespace soda-agent` | Use the namespace value to identify the namespace in which to deploy the agent.
I added an "Optional" tag to those items.

2022-12-02 08:14 UTC, jmarien approved these changes

2022-12-02 18:54 UTC, merged