Change/new agent release
sodadata/docs pull request #730
Opened 2024-02-23 09:32 UTC by s4got10dev

Hi @janet-can @dirkgroenen 

I've made some updated for agent documentation for next release.
Especially:
- Removed mentioning of cronjobs (we don't have them anymore)
- Remove fargate profiles recommendation (we will recommend node groups instead)
- Remove idle mode (we don't support it anymore)

2024-02-23 10:15 UTC, dirkgroenen reviewed
Left some remarks inline, some additional questions/comments:

1. This does not include the required steps for creating a Node Group along with your cluster and setting up the right node size,  right?  We need to make sure to include those as well as otherwise following the steps will result in clusters with no resources to execute the load. 
2.  I would definitely setup a migration guide somewhere for users currently on Fargate which wan't to upgrade `1.0.0` (not 'compatible' with Fargate).  In terms of structure I leave it to @janet-can to decide where best to place it, but you can already go ahead and provide Janet with a draft documentation of those steps so we can write them out more properly.

2024-02-23 10:15 UTC, dirkgroenen commented on soda-agent/deploy.md
>            pollingIntervall: 5
@s4got10dev I think we can get rid of this one as well, as our default is "optimised" for responsiveness right?  If we don't enforce a value in the config we at least give ourselves the flexibility to change the default value in next versions, without having to ask people to revise their helm versions.

2024-02-23 10:15 UTC, dirkgroenen commented on soda-agent/deploy.md
> +We do not recommend to use fargate profiles, because fargate node provisioning will increase job execution time leading not not the best experience.
```suggestion
We advise against using Fargate profiles, as provisioning Fargate nodes extends job execution times, resulting in suboptimal user experiences.
```

2024-02-23 10:15 UTC, dirkgroenen commented on soda-agent/deploy.md
>            pollingIntervall: 5
See comment regarding `pollingInterval`

2024-02-23 20:55 UTC, janet-can approved these changes

2024-02-23 21:04 UTC, janet-can commented on soda-agent/deploy.md
>            pollingIntervall: 5
I'll leave this one in your hands, @dirkgroenen  and @s4got10dev.

2024-02-26 07:24 UTC, dirkgroenen commented on soda-agent/deploy.md
>            pollingIntervall: 5
@s4got10dev yes I would do so. That way we have control over the "default" and not expect everyone to define it via their config values, possibly forgetting or making mistakes leading to slower scan times.

2024-02-26 09:51 UTC, s4got10dev commented on soda-agent/deploy.md
>            pollingIntervall: 5
Done

2024-02-26 09:51 UTC, s4got10dev commented on soda-agent/deploy.md
>            pollingIntervall: 5
Done

2024-02-26 20:31 UTC, janet-can commented
@s4got10dev I added the migration details (CLOUD-6784) to the release notes for 1.0.0 and in the Upgrade docs. I also updated a few parts to include the new log params and remove lingering polling-interval params. I think we're good to go!

2024-02-28 10:10 UTC, dakue-soda requested changes

2024-02-28 10:10 UTC, dakue-soda commented on _release-notes/soda-agent-1.0.0.md
> +    * `soda.scanlauncher.idle.enabled`
Here also `soda.scanlauncher.idle.replicas` should be mentioned or maybe `soda.scanlauncher.idle.*`.

2024-02-28 10:13 UTC, dakue-soda requested changes

2024-02-28 10:13 UTC, dakue-soda commented on _includes/agent-fargate.md
I found this from @janet-can :

```
Actually, that bit about creating a Fargate cluster is all commented out. I've kept it lingering in there for awhile, but have it at least commented out because best practice for documentation is to NOT document other software. Basically, the Soda Agent deployment instructions assume you already have a K8s cluster in which to deploy your soda agent. So: no need to update.
```

If this is the way forward here then I would propose that we remove the tabs for Amazon EKS / Azure AKS and Google GKE from the deployment page because they all now look the same.

2024-02-28 10:16 UTC, dakue-soda commented
Another note here: If we discourage the usage of AWS Fargate we also discourage the usage of Azure virtual nodes. This is not mentioned here but in my opinion if we want to be consistent we should do so? And the other question is what do we do we Google Autopilot where the node management is also done by Google and not under the control of the user?

2024-02-28 13:59 UTC, s4got10dev commented on _includes/agent-fargate.md
> +In Amazon EKS, Soda Agent 1.0.0 favors managed node groups over Fargate profiles. Though this version still functions in Fargate-built clusters, it leads to slower scan times as Fargate must start a
Done

2024-02-28 14:10 UTC, s4got10dev commented on _includes/agent-helm-command.md
> +| `--set soda.agent.target` | (Optional) The cluster the command targets. Use when deploying to `aws-eks` or `azure-aks-virtualnodes`. |
Done

2024-02-28 14:11 UTC, s4got10dev commented on _release-notes/soda-agent-1.0.0.md
> +    * `soda.scanlauncher.idle.enabled`
Done

2024-02-28 14:11 UTC, s4got10dev commented on _release-notes/soda-agent-1.0.0.md
> +    * `externalRedis`
Done

2024-02-28 14:12 UTC, s4got10dev commented on soda/upgrade.md
> +&nbsp;&nbsp;&nbsp;&nbsp;[Upgrade to Soda Agent 1.0.0 or greater](#upgrade-to-soda-agent-100-or-greater)<br />
Done

2024-02-28 14:14 UTC, s4got10dev commented on soda/upgrade.md
> +{% include agent-fargate.md %}
I will leave this one for @janet-can

2024-02-28 14:34 UTC, dirkgroenen commented on _includes/agent-fargate.md
> +2. Check Amazon's recommendations for node size and adapt it for your needs based on volume of scans you anticipate.
```suggestion
2. Check Amazon's recommendations for node size and adapt it for your needs based on volume of scans you anticipate.  We recommend your cluster to have at least 2 CPU and 2GB of RAM, which in general is sufficient to run up to six scans in parallel.
```

Felt like the lack of our recommendation makes it a bit of a shot in the dark.

2024-02-28 14:44 UTC, s4got10dev commented
> Another note here: If we discourage the usage of AWS Fargate we also discourage the usage of Azure virtual nodes. This is not mentioned here but in my opinion if we want to be consistent we should do so? And the other question is what do we do we Google Autopilot where the node management is also done by Google and not under the control of the user?

Unfortunately, I don't have experience with Azure and GCP cluster setup. So if you can @dakue-soda please add some notes/hints on what should we document for those.

2024-02-28 18:12 UTC, janet-can commented on soda/upgrade.md
> +{% include agent-fargate.md %}
Yes, I like to have it more than one place as it covers a few scenarios about how one might go about searching for the info. As

2024-02-28 18:15 UTC, janet-can commented on _includes/agent-fargate.md
There are still the subtlest of differences between the instructions that warranted keeping them separate up until now. However, with this release, it's worth taking a more thorough look at the directions to see if they can all be merged into one and any minor deviations addressed in a more compact way. 

If it's OK, I'll leave this as is for now in the interest of time, and put a Jira for myself to review carefully and adjust/merge as much as possible in a separate PR/effort.

2024-02-29 05:40 UTC, merged