Update dask data source connection
sodadata/docs pull request #882
Opened 2024-09-27 15:10 UTC by teresama

Added new config line needed for dask data source and explanation to it.

2024-09-27 15:31 UTC, bastienboutonnet requested changes
I think we need to be a bit more verbose and reasuring towards our users. This means giving them a liiiiiittle bit more details.

2024-09-27 15:31 UTC, bastienboutonnet commented on soda/connect-dask.md
> +# Config needed to avoid default string conversion to string[pyarrow] see below more info
@teresama I think a bit more reasoning will be needed here. It doesn't have to be all in the comment but maybe say something like "Read More:" and then you would point to the section of the doc that explains a bit more.

2024-09-27 15:31 UTC, bastienboutonnet commented on soda/connect-dask.md
> +The `dask.config.set({"dataframe.convert-string": False})` line is needed due to upgrading `dask>=2023.7.1`.<br /><a href="https://docs.dask.org/en/stable/changelog.html#v2023-7-1">More info here.</a
I don't find this very user-friendly. Can you add a sentence or two with why so that users don't have to go and scour the answer in the link?

2024-09-30 07:12 UTC, teresama commented on soda/connect-dask.md
> +# Config needed to avoid default string conversion to string[pyarrow] see below more info
I added a different comment @bastienboutonnet let me know what you think

2024-09-30 08:59 UTC, bastienboutonnet approved these changes
Looks good to me

Here's a "shipit cat" (it's a cat most of the time) but I am at the mercy of the randomisation gods. 
![](https://i.fluffy.cc/3X84Bq2RR182XcPr0NTKKCp7wvNT8MhD.gif)

2024-09-30 09:03 UTC, merged