added documentation for auto_exclude_anomalies
sodadata/docs pull request #889
Opened 2024-10-07 08:13 UTC by teresama

Added explanation of the flag `auto_exclude_anomalies`

2024-10-07 15:12 UTC, bastienboutonnet requested changes
There's a lot still to explain, and possibly we need to change slighlty the implementation now that I see the param in context it makes me feel that it should be part of `training_dataset_parameters` rather than live in its own section.

This would actually solve one of the issues I point out in the file where you would be able to make your explanation more findable.

2024-10-07 15:12 UTC, bastienboutonnet commented on soda-cl/anomaly-detection.md
> +From `soda-library` version 1.6.4, you can configure Soda to automatically ignore in the training dataset unusual data points (anomalies) by setting the option `auto_exclude_anomalies=True`. With thi
I feel that actually it needs its own section. Now this is a bit in the middle of a haystack.

If you look at how we have structured the documentation page each section of the YAML has it's own anchor point and each parameter gets a generous explanation. I think it would help finding it.

Also this is YAML so it's not `auto_exclude_anomalies=True` but `auto_exclude_anomalies: True`. Users might copy paste this line and end up committing a typo.

Also, maybe a good comparison example would help. What happens when you don't set it to true and what happens when you do (you can simulate it for example and have a graph). I think it would also be nice to have more information in writing about that, for example does the model adapt at all over time? The answer would be yes it does but very very very slowly. If you do let it be included, however, it's much faster.

2024-10-08 07:46 UTC, teresama commented on soda-cl/anomaly-detection.md
> +From `soda-library` version 1.6.4, you can configure Soda to automatically ignore in the training dataset unusual data points (anomalies) by setting the option `auto_exclude_anomalies=True`. With thi
Hi Bastien, makes sense I will add these comments in my next commit. Thanks!

2024-10-09 11:07 UTC, bastienboutonnet approved these changes
From my point of view this looks great now. Please make sure @janet-can signs off on final wording and style.

Here's a "shipit cat" (it's a cat most of the time) but I am at the mercy of the randomisation gods. 
![](https://i.fluffy.cc/hc8WTNRNffFv0fTPJDTdFFbsKMCQn5Rz.gif)

2024-10-09 21:39 UTC, janet-can approved these changes
LGTM!

2024-10-10 08:14 UTC, merged